root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web/"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  exclude_regex = ["_test.go"]

[log]
  time = false

[misc]
  clean_on_exit = true
