version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v5-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v5-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            go test -v -short ./... | tee /tmp/test-reports/unit-tests.txt
      - store_test_results:
          path: /tmp/test-reports

workflows:
  build-and-test:
    jobs:
      - build
